/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.evydhence.calculadora;

/**
 *
 * @author igoro
 */
public class CalculoRoyalties extends javax.swing.JFrame {

    /**
     * Creates new form CalculoRoyalties
     */
    public CalculoRoyalties() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtUNIT = new javax.swing.JTextField();
        txtQNTD = new javax.swing.JTextField();
        txtFAT = new javax.swing.JTextField();
        txtPORC1 = new javax.swing.JTextField();
        lblRESULTADO = new javax.swing.JLabel();
        btnCALCULAR = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtQNTD1 = new javax.swing.JTextField();
        txtUNIT1 = new javax.swing.JTextField();
        txtFAT1 = new javax.swing.JTextField();
        txtPORC2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lblRESULTADOFAT = new javax.swing.JLabel();
        lblRESULTADOFAT1 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lblSOMAQNTD = new javax.swing.JLabel();
        lblSOMAFAT = new javax.swing.JLabel();
        lblENTFAT = new javax.swing.JLabel();
        jlabel1 = new javax.swing.JLabel();
        jlabel2 = new javax.swing.JLabel();
        jlabel3 = new javax.swing.JLabel();
        jlabel4 = new javax.swing.JLabel();
        jlabel5 = new javax.swing.JLabel();
        btnLIMPAR = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtUNIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUNITActionPerformed(evt);
            }
        });

        txtQNTD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQNTDActionPerformed(evt);
            }
        });

        txtFAT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFATActionPerformed(evt);
            }
        });

        txtPORC1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPORC1ActionPerformed(evt);
            }
        });

        lblRESULTADO.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblRESULTADO.setForeground(new java.awt.Color(255, 0, 0));
        lblRESULTADO.setText("0");

        btnCALCULAR.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnCALCULAR.setText("CALCULAR");
        btnCALCULAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCALCULARActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel2.setText("Calculo de Royalties");

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel3.setText("ECV");

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel4.setText("CAUTELAR");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel5.setText("Laudos Emitidos");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel6.setText("Por Laudo");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel7.setText("Faturamento");

        jLabel8.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel8.setText("Cobrada");

        txtQNTD1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQNTD1ActionPerformed(evt);
            }
        });

        txtUNIT1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUNIT1ActionPerformed(evt);
            }
        });

        txtFAT1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFAT1ActionPerformed(evt);
            }
        });

        txtPORC2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPORC2ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel9.setText("O valor a ser faturado é: R$");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/evydhence/calculadora/logotipo.png"))); // NOI18N

        jLabel11.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel11.setText("Entrada de");

        jLabel12.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel12.setText("Quantidade de");

        jLabel13.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel13.setText("Valor Unitário");

        jLabel14.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel14.setText("Porcentagem");

        lblRESULTADOFAT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblRESULTADOFAT.setText("0");

        lblRESULTADOFAT1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblRESULTADOFAT1.setText("0");

        jLabel15.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel15.setText("Faturamento ");

        jLabel18.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel18.setText("Gerado");

        jLabel16.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel16.setText("TOTAL");

        lblSOMAQNTD.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblSOMAQNTD.setText("0");

        lblSOMAFAT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblSOMAFAT.setText("0");

        lblENTFAT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblENTFAT.setText("0");

        jlabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlabel1.setText("R$:");

        jlabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlabel2.setText("R$:");

        jlabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlabel3.setText("Qntd:");

        jlabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlabel4.setText("R$:");

        jlabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlabel5.setText("R$:");

        btnLIMPAR.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnLIMPAR.setText("LIMPAR");
        btnLIMPAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLIMPARActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addComponent(jLabel3))
                                    .addComponent(jLabel4))
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtQNTD, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtQNTD1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addComponent(jlabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblSOMAQNTD))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel12)))
                                .addGap(27, 27, 27)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(184, 184, 184))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(217, 217, 217))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(268, 268, 268))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel6)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                                                                .addComponent(txtUNIT1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                            .addComponent(txtUNIT, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGap(48, 48, 48)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jlabel4)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(lblRESULTADOFAT))
                                                            .addComponent(jLabel18)
                                                            .addComponent(jLabel15)
                                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                .addGroup(layout.createSequentialGroup()
                                                                    .addComponent(jlabel2)
                                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                    .addComponent(lblSOMAFAT))
                                                                .addGroup(layout.createSequentialGroup()
                                                                    .addComponent(jlabel5)
                                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                    .addComponent(lblRESULTADOFAT1))))))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(txtFAT, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(jLabel7)
                                                            .addComponent(jLabel11)
                                                            .addComponent(txtFAT1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGap(45, 45, 45)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                            .addComponent(jLabel8)
                                                            .addGroup(layout.createSequentialGroup()
                                                                .addGap(1, 1, 1)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                    .addComponent(txtPORC1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                    .addComponent(txtPORC2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                            .addComponent(jLabel14)))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jlabel1)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(lblENTFAT))))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(btnLIMPAR)
                                                .addGap(156, 156, 156)))
                                        .addGap(29, 29, 29))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnCALCULAR)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblRESULTADO)))
                        .addGap(32, 32, 32))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel18))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUNIT, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFAT, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPORC1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtQNTD, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(lblRESULTADOFAT)
                    .addComponent(jlabel4))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtQNTD1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUNIT1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFAT1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPORC2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRESULTADOFAT1)
                    .addComponent(jlabel5))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(lblSOMAQNTD)
                    .addComponent(lblSOMAFAT)
                    .addComponent(lblENTFAT)
                    .addComponent(jlabel1)
                    .addComponent(jlabel2)
                    .addComponent(jlabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCALCULAR)
                    .addComponent(btnLIMPAR))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(lblRESULTADO))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUNITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUNITActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUNITActionPerformed

    private void txtQNTDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQNTDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQNTDActionPerformed

    private void txtFATActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFATActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFATActionPerformed

    private void txtPORC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPORC1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPORC1ActionPerformed

    private void btnCALCULARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCALCULARActionPerformed
        //CAPTURA DE DADOS
        
        String qntd = txtQNTD.getText();
        String unit = txtUNIT.getText();
        String fat = txtFAT.getText();
        String porc1 = txtPORC1.getText();
        
        String qntd1 = txtQNTD1.getText();
        String unit1 = txtUNIT1.getText();
        String fat1 = txtFAT1.getText();
        String porc2 = txtPORC2.getText();
        
        //se estiver preenchido
        if(!qntd.equals("")) {
            if(!unit.equals("")){
                if(!porc1.equals("")){
                    if(!qntd1.equals("")) {
                        if(!unit1.equals("")){
                            if(!porc2.equals("")){
                                //Calculos ECV
                                int quantidade = Integer.parseInt(qntd);
                                int unitario = Integer.parseInt(unit);
                                int porcentagem = Integer.parseInt(porc1);
                                int faturamento = quantidade * unitario;
                                float somaP = (float) (porcentagem * 0.0100);
                                float somamedia1 = faturamento * somaP;
                                
                                //Calculos Cautelar
                                int quantidade1 = Integer.parseInt(qntd1);
                                int unitario1 = Integer.parseInt(unit1);
                                int porcentagem1 = Integer.parseInt(porc2);
                                int faturamento1 = quantidade1 * unitario1;
                                float somaP1 = (float) (porcentagem1 * 0.0100);
                                float somamedia2 = faturamento1 * somaP1;
                                
                                //Soma de colunas
                                int somaqntd = quantidade + quantidade1;
                                float somafat = (float)(faturamento + faturamento1);
                                     
                                //Soma ECV + Cautelar
                                float somaTotal = somamedia1 + somamedia2;

                                lblRESULTADO.setText(Float.toString(somaTotal));
                                lblRESULTADOFAT.setText(Float.toString(faturamento));
                                lblRESULTADOFAT1.setText(Float.toString(faturamento1));
                                lblSOMAQNTD.setText(Integer.toString(somaqntd));
                                lblSOMAFAT.setText(Float.toString(somafat));
                                                                
                            }
                        }
                    }
                }
            }
        }
        else if(!fat.equals("")) {
            if(!porc1.equals("")){
                if(!fat1.equals("")) {
                    if(!porc2.equals("")) {
                        //Calculo ECV
                        float faturamento = Float.parseFloat(fat);
                        int porcentagem = Integer.parseInt(porc1);
                        float somaP = (float) (porcentagem * 0.0100);
                        float somamedia1= faturamento * somaP;
                        
                        //Calculo Cautelar
                        float faturamento1 = Float.parseFloat(fat1);
                        int porcentagem1 = Integer.parseInt(porc2);
                        float somaP1 = (float) (porcentagem1 * 0.0100);
                        float somamedia2= faturamento1 * somaP1;
                        
                        //Soma de colunas
                        float entfat = (float)(faturamento + faturamento1);
                        
                        //Calculo ECV + Cautelar
                        float somaTotal = somamedia1 + somamedia2;
                        
                        lblRESULTADO.setText(Float.toString(somaTotal));
                        lblENTFAT.setText(Float.toString(entfat));
                        
                    }
                }
            }
        }
                   
             
       //FIM DO CÓDIGO
       
 
    }//GEN-LAST:event_btnCALCULARActionPerformed

    private void txtQNTD1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQNTD1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQNTD1ActionPerformed

    private void txtUNIT1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUNIT1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUNIT1ActionPerformed

    private void txtFAT1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFAT1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFAT1ActionPerformed

    private void txtPORC2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPORC2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPORC2ActionPerformed

    private void btnLIMPARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLIMPARActionPerformed
           //Botão Limpar
           txtQNTD.setText(null);
           txtUNIT.setText(null);
           txtFAT.setText(null);
           txtPORC1.setText(null);
           txtQNTD1.setText(null);
           txtUNIT1.setText(null);
           txtFAT1.setText(null);
           txtPORC2.setText(null);
           lblRESULTADO.setText("0");
           lblSOMAQNTD.setText("0");
           lblRESULTADOFAT.setText("0");
           lblRESULTADOFAT1.setText("0");
           lblSOMAFAT.setText("0");
           lblENTFAT.setText("0");
           
    }//GEN-LAST:event_btnLIMPARActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculoRoyalties.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculoRoyalties.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculoRoyalties.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculoRoyalties.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculoRoyalties().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCALCULAR;
    private javax.swing.JButton btnLIMPAR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jlabel1;
    private javax.swing.JLabel jlabel2;
    private javax.swing.JLabel jlabel3;
    private javax.swing.JLabel jlabel4;
    private javax.swing.JLabel jlabel5;
    private javax.swing.JLabel lblENTFAT;
    private javax.swing.JLabel lblRESULTADO;
    private javax.swing.JLabel lblRESULTADOFAT;
    private javax.swing.JLabel lblRESULTADOFAT1;
    private javax.swing.JLabel lblSOMAFAT;
    private javax.swing.JLabel lblSOMAQNTD;
    private javax.swing.JTextField txtFAT;
    private javax.swing.JTextField txtFAT1;
    private javax.swing.JTextField txtPORC1;
    private javax.swing.JTextField txtPORC2;
    private javax.swing.JTextField txtQNTD;
    private javax.swing.JTextField txtQNTD1;
    private javax.swing.JTextField txtUNIT;
    private javax.swing.JTextField txtUNIT1;
    // End of variables declaration//GEN-END:variables
}
